Create plant
tasnimzotder/hacktoberfest-2020 pull request #144
Opened 2020-10-15 11:37 UTC by kosakanishkdev

plant trees

2020-10-15 11:54 UTC, tasnimzotder commented on python/plant
> +deforest == 0
hey @kosakanishkdev here we got some error -
```suggestion
afforest = 1
deforest = 0
```

2020-10-15 11:56 UTC, tasnimzotder requested changes
@kosakanishkdev Can you please change `python/plant` to `python/plant.py` that is adding the `.py` extension.

2020-10-15 17:33 UTC, kosakanishkdev commented
got up with the changes

2020-10-15 17:36 UTC, tasnimzotder commented
That's good @kosakanishkdev.


Just one more work to do -
Change `python/plant` to `python/plant.py`

2020-10-16 17:36 UTC, tasnimzotder approved these changes

2020-10-16 17:37 UTC, merged