mergeddd plis
tasnimzotder/hacktoberfest-2020 pull request #178
Opened 2020-10-21 19:01 UTC by Youshiro

2020-10-21 19:07 UTC, tasnimzotder requested changes
hey @Youshiro, you need to include the image named `aashutosh.jpg`

2020-10-22 18:21 UTC, Youshiro commented
I changed the name of the image and uploaded it

2020-10-23 04:31 UTC, tasnimzotder commented
Thanks.

2020-10-23 04:32 UTC, tasnimzotder approved these changes

2020-10-23 04:32 UTC, merged