[thank for hacktoberfest]
tasnimzotder/hacktoberfest-2020 pull request #211
Opened 2020-10-27 04:23 UTC by ITreeMan

First time hacktoberfest

2020-10-27 04:36 UTC, tasnimzotder requested changes
hey @ITreeMan, thanks for your interest. With your PR some unwanted files were added.
Delete the following files and make a commit.

1. `.DS_Store`
1. `_hackbars/.DS_Store`
1. `assets/.DS_Store`
1. `assets/images/.DS_Store`

2020-10-28 05:09 UTC, ITreeMan commented
Sorry.  I delete the following files and make a new commit.

2020-10-28 07:01 UTC, tasnimzotder commented
You did that right.
You just need to delete another file `_hackbars/.DS_Store`

2020-10-30 09:47 UTC, ITreeMan commented
I'm delete _hackbars/.DS_Store

2020-10-30 16:17 UTC, tasnimzotder commented on _hackbars/ITreeMan.md
> +## <!-- Your MESSAGE on climate change -->
I did not notice it.

Can you add your __MESSAGE__ on climate change?

2020-10-30 17:25 UTC, ITreeMan commented
I add my MESSAGE on climate change.

2020-10-30 18:40 UTC, tasnimzotder approved these changes

2020-10-30 18:41 UTC, merged

2020-10-30 18:41 UTC, tasnimzotder commented
Thanks for your contributions :)